<<<<<<< HEAD
TRAIN:
    SAMPLE_RATE:16000
    FFT_LEN:512
    HOP_LEN:256
    FMIN:20
    FMAX:8000
    MELS:80
    DURATION:2
    CSV_PATH:"./dataset/"

TEST:
=======
TRAIN:
    SAMPLE_RATE:16000
    FMIN:20
    FMAX:8000
    MELS:80
    LENGTH:2

TEST:
>>>>>>> e388a991089d83481569c3e972ca094d6db0d172
    